Feature/ap 3948
apromore/ApromoreCode pull request #1072
Opened 2021-07-07 08:17 UTC by dreamind

2021-07-07 08:18 UTC, dreamind commented
I probably need to run through some parts of this PR

2021-07-08 08:47 UTC, raboczi requested changes
Goodness, there's a lot of work here.

I have a repetitive comment "Localize messagebox title" which would probably be most easily addressed by doing something similar to `dashboard.util.ZKMessageCtrl` or `org.apromore.portal.common.notification.Notification` and having some static utility methods.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/common/i18n/I18nConfig.java
> +        // System.out.println(dateTimePatterns);
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/common/i18n/I18nConfig.java
> +//            }
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/common/i18n/I18nSession.java
> +}
This seems to be unused and is rather weird.  Future plans for it, or experimental code that can be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/BPMNEditorController.java
> +            }
We should be mapping specific locales like en_us to more general locales like en rather than the other way around.  Otherwise every single language is going to require an ad-hoc mapping like this one.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/BaseListboxController.java
> +				Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
It would probably be better to localize the Messagebox title.  Possibly in a similar centralized way to how Chii does it in dashboard.util.ZKMessageCtrl.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/BaseListboxController.java
> +			    Notification.error(Labels.getLabel("portal_selectOneLog_message"));
Would it make sense to move the `Labels.getLabel` lookup inside of `Notification.error`?  Since every notification _ought_ to be localized, make it inconvenient to do it the wrong way.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/MainController.java
> +import java.util.*;
Our Checkstyle rules currently include [AvoidStarImport](https://checkstyle.org/config_imports.html#AvoidStarImport) so if your IDE is set to automatically collapse them, see if you can set it not to.  It'll make things even harder to eventually enable style checking.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/MainController.java
> +import org.zkoss.zul.*;
Again, we should honor [AvoidStarImport](https://checkstyle.org/config_imports.html#AvoidStarImport).

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/MainController.java
> +            Messagebox.show(Labels.getLabel("portal_repoUnvailable_message"),
The key should probably be spelled `portal_repoUnavailable_message`.  I'm assuming not using `MessageFormat.format` to include `message` is intentional.  You can remove all the preceding code that populates `message` and all the `e.printStackTrace();` calls, since the stack trace is already captured by `LOGGER.error`.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/MainController.java
> +                Messagebox.show(sb.toString(), "Apromore Plugin", Messagebox.OK, Messagebox.EXCLAMATION);
The message title is user-visible natural language text, so it ought to be subject to i18n too.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/MenuController.java
> +                            + URLEncoder.encode(itemCode, "utf-8") + "/"
If we did `import static  java.nio.charset.StandardCharsets.UTF_8;` then could replace `"utf-8"` with `UTF_8`.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/SaveAsDialogController.java
> +            Messagebox.show(Labels.getLabel("portal_unableSave_message"), null, Messagebox.OK, Messagebox.ERROR);
We should log the error to capture the stack trace, i.e. `LOGGER.error("Unable to save mode", e);`

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/UserMenuController.java
> +              + URLEncoder.encode(plugin.getItemCode(Locale.getDefault()), "utf-8") + "/"
Again, could pull `UTF_8` constant in from `StandardCharsets`.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/renderer/SummaryItemRenderer.java
>          }
Perhaps absorb this logic into `DateTimeUtils.normalize(String, DateTimeFormatter)` in the case that it's passed `null` as the formatter.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/AddFolderController.java
> +            Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
Should localize the messagebox title and should log the exception.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/AddFolderController.java
> +                Messagebox.show(Labels.getLabel("portal_noEmptyName_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/AddFolderController.java
> +            // Messagebox.show(Labels.getLabel("portal_invalidValue_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Can this be removed, or uncommented?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/AddFolderController.java
> +                Messagebox.show(Labels.getLabel("portal_noAuthorizedRename_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/CopyAndPasteController.java
> +                Messagebox.show(Labels.getLabel("portal_failedCut_message"), "Apromore", Messagebox.OK,
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/CopyAndPasteController.java
> +                Messagebox.show(Labels.getLabel("portal_failedCopy_message"), "Apromore", Messagebox.OK,
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/CopyAndPasteController.java
> +            Messagebox.show(Labels.getLabel("portal_failedPaste_message"), "Apromore", Messagebox.OK,
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/RenameFolderController.java
> +                Messagebox.show(Labels.getLabel("portal_noEmptyName_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/RenameFolderController.java
> +            // Messagebox.show(Labels.getLabel("portal_invalidValue_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Can this be removed or uncommented?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/RenameFolderController.java
> +                Messagebox.show(Labels.getLabel("portal_noAuthorizedRename_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/webapp/WEB-INF/zk-label.properties
> +portal_deleteFolderPrompt_message = Are you sure you want to delete selected folder(s) and all it's contents?
"it's" should be "its".

2021-07-08 08:47 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/webapp/themes/ap/editor/css/icons.css
> +    /* background-image: url('../../common/img/icons/save.svg') !important; */
Can this (and the following similarly-commented-out background-image attributes) be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/AccessControlPlugin.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/AccessControlPlugin.java
> +            Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title and log exception to catch the stack trace.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/controllers/AccessController.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/controllers/AccessController.java
> +                    Messagebox.show(getLabel("failedUpdatePermission_message"), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/controllers/AccessController.java
>                      LOGGER.error("Something is wrong in updating access");
`LOGGER.error("Something is wrong in updating access", e);`

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/controllers/AccessController.java
> +            "Apromore",
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Account-Portal-Plugin/src/main/java/org/apromore/plugin/portal/account/ChangePasswordController.java
> +            Messagebox.show("Unable to edit account", "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/File-Portal-Plugin/src/main/java/org/apromore/plugin/portal/file/UploadFilePlugin.java
> +            Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Merge-Portal-Plugin/src/main/java/org/apromore/plugin/merge/portal/MergePlugin.java
> +
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Merge-Portal-Plugin/src/main/java/org/apromore/plugin/merge/portal/MergePlugin.java
> +            Messagebox.show(message, "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/PDController.java
> +import java.util.*;
As before, AvoidStarImport.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/PDController.java
> +            LOGGER.error("An error occurred while initializing UI: " + ex.getMessage());
`LOGGER.error("An error occurred while initializing UI", ex);`

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/PDController.java
> +            LOGGER.error("Errors occured while updating UI: " + ex.getMessage());
`LOGGER.error("Errors occured while updating UI", ex);`

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/PDController.java
> +                // LOGGER.error("Error when undoing filter action. Error message: " + e.getMessage());
Can this be removed, or better, uncommented?  If uncommented, include `ex` in the logging call.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/actions/FilterActionOnClearFilter.java
> +            // LOGGER.error("Error in clearing filter. Error message: " + e.getMessage());
Can this be removed, or better, uncommented? If uncommented, include `e` in the logging call.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/actions/FilterActionOnCompositeFilterCriteria.java
> +            // LOGGER.error("Error in filtering. Error message: " + e.getMessage());
Can this be removed, or better, uncommented? If uncommented, include `e` in the logging call.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/actions/FilterActionOnElementFilter.java
> +            // LOGGER.error("Error in filtering. Error message: " + e.getMessage());
Can this be removed, or better, uncommented? If uncommented, include `e` in the logging call.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/components/CaseDetailsController.java
> +						// LOGGER.error(e.getMessage());
Can this be removed, or better, uncommented? If uncommented, include `e` in the logging call.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/components/GraphSettingsController.java
> +    private String[] orderingLabels; // = Labels.getLabel("e.pd.orderCaseFreq.text").split(",");
Can the commented-out code be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/components/GraphSettingsController.java
> +                // orderingLabels = Labels.getLabel("e.pd.orderCaseFreq.text").split(",");
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/components/GraphSettingsController.java
> +                // orderingLabels = Labels.getLabel("e.pd.orderDuration.text").split(",");
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/components/GraphSettingsController.java
> +                // orderingLabels = Labels.getLabel("e.pd.orderCaseVariant.text").split(",");
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/components/ViewSettingsController.java
> +                // String value = Labels.getLabel("e.pd.perspective." + key.replace(':', '.') + ".hint", key);
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/eventlisteners/BPMNExportController.java
> +                    Messagebox.show(parent.getLabel("failedAnnotateBPMN_message"), "Apromore", Messagebox.OK, Messagebox.EXCLAMATION);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/eventlisteners/BPMNExportController.java
> +                            );
Any reason not to put this on one line?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Process-Discoverer-Portal-Plugin/src/main/java/org/apromore/plugin/portal/processdiscoverer/eventlisteners/LogExportController.java
> +            // Labels.getLabel("e.pd.saveLogWin.text"), // "Save filtered log",
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Similarity-Search-Portal-Plugin/src/main/java/org/apromore/plugin/similaritysearch/portal/SimilaritySearchPlugin.java
> +//    }
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/Similarity-Search-Portal-Plugin/src/main/java/org/apromore/plugin/similaritysearch/portal/SimilaritySearchPlugin.java
> +            Messagebox.show(message, "Apromore", Messagebox.OK, Messagebox.ERROR);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/CreateGroupController.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/CreateUserController.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/DeleteUserController.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/DeleteUserController.java
> +                    "Apromore", Messagebox.OK, Messagebox.INFORMATION);
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminController.java
> +import java.util.*;
AvoidStarImports

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminController.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminController.java
> +                    "Apromore",
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminController.java
> +                "Apromore",
Localize messagebox title.

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminPlugin.java
> +import java.util.*;
AvoidStarImport

2021-07-08 08:47 UTC, raboczi commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminPlugin.java
> +        // Locale locale = Locales.getCurrent()
Can this be removed?

2021-07-09 13:22 UTC, dreamind commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/BaseListboxController.java
> +				Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
I agree with this, but I would like to address it in separate ticket and do the second pass changes for the messagebox.

2021-07-09 13:41 UTC, dreamind commented on Apromore-Custom-Plugins/User-Admin-Portal-Plugin/src/main/java/org/apromore/plugin/portal/useradmin/UserAdminController.java
> +                    "Apromore",
Will do in a separate ticket

2021-07-09 13:43 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/workspaceOptions/AddFolderController.java
> +            Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
Defer localizing the title, but logging the exception may still be a good idea.

2021-07-09 13:43 UTC, raboczi commented on Apromore-Custom-Plugins/Access-Control-Portal-Plugin/src/main/java/org/apromore/plugin/portal/accesscontrol/AccessControlPlugin.java
> +            Messagebox.show(e.getMessage(), "Apromore", Messagebox.OK, Messagebox.ERROR);
Defer localizing the title, but logging the exception may still be a good idea.

2021-07-09 13:58 UTC, dreamind commented
Reviewed and updated

2021-07-10 00:44 UTC, raboczi approved these changes
I'm satisfied that my previous change requests and review comments have been considered.  Good to merge!

2021-07-12 01:06 UTC, merged