AP-5427 Add aux custom element
apromore/ApromoreCode pull request #1581
Opened 2021-12-29 04:52 UTC by dreamind

2022-01-03 23:16 UTC, Janite requested changes
Images can be added and resized as expected. Attachment tab looks good. Just have a few comments/questions:

1. Is there a way to remove icons and uploaded images once they have been added?
2. A link added to an element redirects to a page in apromore portal instead of the direct link text added. Wanted to check if this is intended.
3. The white background of the x's used to clear the link text and url overlap the text input border.

2022-01-03 23:16 UTC, Janite commented on Apromore-Core-Components/Apromore-BPMN-Editor/Apromore-BPMN-Modeler-JS/app/provider/entries/aux/AuxEntries.js
> +//  var img = extensionElements.values.filter(function(e) {
Can we remove this comment from the code?

2022-01-04 04:45 UTC, dreamind commented on Apromore-Core-Components/Apromore-BPMN-Editor/Apromore-BPMN-Modeler-JS/app/provider/entries/aux/AuxEntries.js
> +//  var img = extensionElements.values.filter(function(e) {
Feedback have been implemented

2022-01-05 01:25 UTC, Janite approved these changes
Looks good and works as expected.

2022-01-05 01:52 UTC, merged