Feature/ap5555 api spring boot migration
apromore/ApromoreCode pull request #1658
Opened 2022-01-28 01:39 UTC by jamesjin2021

This is a PR for Springboot migration for existing REST-Endpoint module (Jersey based). Some changes are introduced to ApromoreCore to allow API requests/Swagger requests pass through and enhance backend services.

2022-01-31 01:36 UTC, lahiru-maha commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/config/PortalKeyCloakSecurity.java
> +    http.csrf().ignoringAntMatchers("/zkau", "/rest", "/rest/*", "/rest/**/*", "/zkau/*", "/bpmneditor/editor/*")
Is it worth externalising these to be read from application config?

2022-01-31 01:38 UTC, lahiru-maha commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/config/PortalSecurityConfig.java
> +  private static final String[] SWAGGER2_AUTH_WHITELIST = {
Seems like PortalSecurityConfig and PortalKeyCloakSecurity both share the same whitelists? Would be worth adding to a common whitelist constants, or define in an externalised application configuration.

2022-02-08 22:41 UTC, lahiru-maha commented on Apromore-Core-Components/Apromore-Manager/src/main/java/org/apromore/security/impl/UsernamePasswordAuthenticationProvider.java
> +import java.util.*;
Minor one, but its actually better to have the individual imports than *

2022-02-10 00:19 UTC, raboczi commented on Apromore-Database/src/main/resources/db/migration/changeLog-Data-RestAPI.yaml
> +    author:  "add new test user to user table"
In all these author fields, you are the author.

2022-02-10 00:21 UTC, raboczi commented on Apromore-Database/src/main/resources/db/migration/changeLog-RestAPI.yaml
> +       author: init-data
In all these author fields, you are the author.

2022-02-10 00:25 UTC, raboczi requested changes
I'm pretty sure all the HTTP error pages in Apromore-Core-Components/Apromore-Portal/src/main/webapp/pages/ (e.g. 404.html, 500.html) ought to be .zul files instead.  Surely that raw ZK Javascript wasn't written by hand.

2022-02-10 06:58 UTC, jamesjin2021 commented
> I'm pretty sure all the HTTP error pages in Apromore-Core-Components/Apromore-Portal/src/main/webapp/pages/ (e.g. 404.html, 500.html) ought to be .zul files instead. Surely that raw ZK Javascript wasn't written by hand.

Author fields have been updated.

2022-02-10 23:15 UTC, raboczi approved these changes
This is half the size it started out as, which is great.

2022-02-10 23:45 UTC, jamesjin2021 commented
looks good. remaining issues would be tracked by Jira cards.

2022-02-13 22:59 UTC, jamesjin2021 commented
code looks good, merge now.

2022-02-13 23:01 UTC, merged