AP-5922 Mulitple session handle from Portal
apromore/ApromoreCode pull request #1773
Opened 2022-02-26 13:19 UTC by shapon2004

2022-02-27 01:28 UTC, shapon2004 commented
To resolve the session related issue, following options has been implemented:

1) Multiple portalContext will be stored into session for multiple Portal tabs.(ex: Sessions.getCurrent().setAttribute("portalContext_" + Desktop_Id, portalContext))

2) To access the portalContext, other tabs like dashboard or PD will have to include reference of the portal into Url (ex: dashboard/index.zul?REFER_ID=Desktop_Id)

3) During creation of other tabs(excluding Portal), a new ZK desktop attribute has been added to set related parent portal (ex:  desktop.setAttribute("PORTAL_REF_ID",Desktop_Id))

4) To retrieve related portalContext: We call first desktop.getAttribute("PORTAL_REF_ID") to retrieve parent portal reference and thenusing the reference we identify the related portalContext from session (ex: Sessions.getCurrent().getAttribute("portalContext_"+Desktop_Id))

5) For portal, we have added a listner into Maincontroller to cleanup the sesion portalContext related object.

6) All the class/object will get the portalContext from PortalContextHolder.getActivePortalContext() static method. This method has the mechanism to retrieve the portalContext from current tabs.

2022-02-28 02:00 UTC, raboczi requested changes
There seem to be tabs introduced into the source code again, e.g. in the new PortalContextHolder.

My preliminary testing turned up an exception when opening Dashboard tabs.  I should be able to demonstrate that to you if needed.

2022-02-28 02:00 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/context/PluginPortalContext.java
> +        //Session session = desktop.getSession();
Reasonable to remove this commented-out code?

2022-02-28 02:00 UTC, raboczi commented on Apromore-Plugins/plugin-core/portal/api/src/main/java/org/apromore/plugin/portal/PortalUrlWrapper.java
> +        }
Perhaps java.net.URI should be used here to incorporate some validation?  The conditional check would become something like `URI uri = new URI(url); if (uri.getQuery() == null) { ...`.  It'd be a bit verbose, but the output could be composed using a URI instance as well.

2022-02-28 02:11 UTC, shapon2004 commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/context/PluginPortalContext.java
> +        //Session session = desktop.getSession();
Yeah. I am removing it.

2022-02-28 05:36 UTC, raboczi commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/context/PluginPortalContext.java
> +        //Session session = desktop.getSession();
Passes for me now.

2022-02-28 05:37 UTC, raboczi approved these changes
This seems to address the defect and is fairly tidy.  Approved!

2022-02-28 05:40 UTC, merged