Merge Simulation related fixing/improvment into release 8.4.1
apromore/ApromoreCode pull request #2260
Opened 2022-07-25 08:26 UTC by shapon2004

2022-07-25 08:53 UTC, shapon2004 commented
AP-6446 Sim parameters: limit total number of instances to be simulated
AP-6447 Discover hourly cost information from event log and use in sim parameters
AP-3821 Change error message of simulation timeframe

2022-07-25 23:19 UTC, Janite requested changes

2022-07-25 23:19 UTC, Janite commented on Apromore-Custom-Plugins/Process-Simulation-Info-Logic/src/main/java/org/apromore/processsimulation/config/SimulationAdditionalParam.java
> +
This should be the license header for ApromoreCore

2022-07-25 23:19 UTC, Janite commented on Apromore-Core-Components/Apromore-Portal/src/main/webapp/openModelInBPMNio.zul
> +          Apromore.BPMNEditor.qbpProcessMaxLimit = (${arg.qbpProcessMaxLimit})?${arg.qbpProcessMaxLimit}:25000;
Can you also add the change from https://github.com/apromore/ApromoreEE/pull/1702? This fixes an issue where `qbpProcessMaxLimit` is not found when we open models in publish mode.

2022-07-25 23:19 UTC, Janite commented on Apromore-Custom-Plugins/Process-Simulation-Info-Logic/src/main/java/org/apromore/processsimulation/model/CostingData.java
> + */
This should be the license header for ApromoreCore

2022-07-26 01:27 UTC, Janite approved these changes
Looks good!

2022-07-26 01:31 UTC, merged