AP-2234 Immediately process search on combobox select
apromore/ApromoreCode pull request #491
Opened 2020-10-04 22:19 UTC by dreamind

2020-10-04 23:40 UTC, nolantellis approved these changes

2020-10-05 20:22 UTC, hoangnguyen7x requested changes

2020-10-05 20:22 UTC, hoangnguyen7x commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/SimpleSearchController.java
> +                processSearch();
As this system-wide "search" function requires extensive queries affecting performance, it is not recommended to perform immediately after the keyword is selected.

2020-10-05 20:22 UTC, hoangnguyen7x commented on Apromore-Core-Components/Apromore-Portal/src/main/java/org/apromore/portal/dialogController/SimpleSearchController.java
> +                processSearch();
Another usability issue to consider is: as soon as a previous keyword is selected (e.g. "sepsis diagnosis_CRP"), the system searches and returns a result; however, this previous keyword is only selected to be refined, the actual keywords the user wants to use is: "sepsis case_short diagnosis_CRP". This action thus results in an unnecessary system search (could involve a waiting hourglass) which is an inefficient UI choice.

2020-10-05 23:15 UTC, dreamind commented
Close the PR for now

2020-10-05 23:15 UTC, closed without merging