Feature/custom calender/ap 2395
apromore/ApromoreCode pull request #544
Opened 2020-11-06 01:59 UTC by nolantellis

* Added Holiday with tests
* Added logic to calculate duration
* This does not effect any development features.

2020-11-06 23:06 UTC, dreamind commented on Apromore-Calendar/src/main/java/org/apromore/calendar/service/CustomCalendarService.java
> +  public CalenderModel getCalenderById(Long id) {
Calendar instead of Calender?

2020-11-06 23:20 UTC, dreamind commented
While all the workday and holiday definition is set in UTC, should we add the TimeZone to the CalendarModel?
Is the duration calculated in the UTC context? To account for TimeZone specific quirks (like daylight saving) should we use ZonedDateTime (and perhaps ChronoUnit.between)?

2020-11-08 22:43 UTC, raboczi requested changes
As already noted by Ivo, CalenderModel needs to be renamed as CalendarModel.  Additionally, you should configure your IDE to indent with spaces rather than tabs; it seems to keep rewriting swathes of XML.

2020-11-09 01:17 UTC, nolantellis commented on Apromore-Calendar/src/main/java/org/apromore/calendar/service/CustomCalendarService.java
> +  public CalenderModel getCalenderById(Long id) {
Corrected.

2020-11-09 01:17 UTC, nolantellis commented
> While all the workday and holiday definition is set in UTC, should we add the TimeZone to the CalendarModel?
> Is the duration calculated in the UTC context? To account for TimeZone specific quirks (like daylight saving) should we use ZonedDateTime (and perhaps ChronoUnit.between)?

You are right. I will merge this changes which does not effect anything. I have created another task to convert it to ZonedDateTime

2020-11-09 02:55 UTC, dreamind approved these changes

2020-11-09 03:13 UTC, raboczi approved these changes
Good enough to merge!

2020-11-09 03:15 UTC, merged