Add support to rename only if authorized
apromore/ApromoreCode pull request #601
Opened 2020-12-07 22:56 UTC by nolantellis

2020-12-07 23:24 UTC, raboczi approved these changes
This looks fine.  One quibble: did you intentionally reindent BaseListboxController?  Eventually I'd like to enable checkstyle and ban tab characters.

2020-12-08 00:36 UTC, frank-ma-leonardo requested changes
A user with VIEWER access type can't rename log, process and folder as expected. However, there is casualty that user with proper access type can not rename a folder.

2020-12-08 01:12 UTC, nolantellis commented
> A user with VIEWER access type can't rename log, process and folder as expected. However, there is casualty that user with proper access type can not rename a folder.

This is in dev too, Have fixed it

2020-12-08 01:15 UTC, frank-ma-leonardo approved these changes

2020-12-08 01:16 UTC, merged